-- En este archivo deben estar tus ejercicios de consultas sql

/* **Empleados ordenados alfabéticamente (Z...A):** */
SELECT NOMBRES FROM EMPLEADOS ORDER BY NOMBRES DESC;


/* 2. **Empleados de Soporte:**   */
SELECT EMPLEADOS.NOMBRES, PUESTOS.PUESTO, LOCALIDADES.LOCALIDAD 
FROM EMPLEADOS, PUESTOS, LOCALIDADES 
WHERE EMPLEADOS.PUESTO_ID = PUESTOS.ID 
AND PUESTOS.PUESTO = 'Soporte' 
AND PUESTOS.LOCALIDAD_ID = LOCALIDADES.ID;


/* 3. **Nombres que terminan con 'o':**   */
SELECT NOMBRES 
FROM EMPLEADOS 
WHERE NOMBRES LIKE '%o';


/* 4. **Empleados en Carlos Paz:**   */
SELECT EMPLEADOS.NOMBRES, EMPLEADOS.SUELDO, LOCALIDADES.LOCALIDAD 
FROM EMPLEADOS, DEPARTAMENTOS, LOCALIDADES 
WHERE EMPLEADOS.DEPARTAMENTO_ID = DEPARTAMENTOS.ID 
AND DEPARTAMENTOS.LOCALIDAD_ID = LOCALIDADES.ID 
AND LOCALIDADES.LOCALIDAD = 'Carlos Paz';


/* 5. **Sueldos entre 10000 y 13000:**   */
SELECT EMPLEADOS.NOMBRES, EMPLEADOS.SUELDO, LOCALIDADES.LOCALIDAD 
FROM EMPLEADOS, DEPARTAMENTOS, LOCALIDADES 
WHERE EMPLEADOS.DEPARTAMENTO_ID = DEPARTAMENTOS.ID 
AND DEPARTAMENTOS.LOCALIDAD_ID = LOCALIDADES.ID 
AND EMPLEADOS.SUELDO BETWEEN 10000 AND 13000;


/* 6. **Departamentos con más de 5 empleados:**  */
SELECT DEPARTAMENTOS.ID 
FROM EMPLEADOS, DEPARTAMENTOS 
WHERE EMPLEADOS.DEPARTAMENTO_ID = DEPARTAMENTOS.ID 
GROUP BY DEPARTAMENTOS.ID 
HAVING COUNT(*) > 5;


/* 7. **Empleados en Córdoba con puesto de Analista o Programador:**   */
SELECT EMPLEADOS.NOMBRES 
FROM EMPLEADOS, DEPARTAMENTOS, LOCALIDADES, PUESTOS 
WHERE EMPLEADOS.DEPARTAMENTO_ID = DEPARTAMENTOS.ID 
AND DEPARTAMENTOS.LOCALIDAD_ID = LOCALIDADES.ID 
AND LOCALIDADES.LOCALIDAD = 'Córdoba' 
AND EMPLEADOS.PUESTO_ID = PUESTOS.ID 
AND (PUESTOS.PUESTO = 'Analista' OR PUESTOS.PUESTO = 'Programador');


/* 8. **Sueldo medio de todos los empleados:**  */ 
SELECT AVG(SUELDO) AS SUELO_MEDIO
FROM EMPLEADOS; 


/* 9. **Máximo sueldo en el departamento 10:**   */
SELECT MAX(SUELDO) AS MAX_SUELDO_DEPTO_10
FROM EMPLEADOS 
WHERE DEPARTAMENTO_ID = 10;


/* 10. **Sueldo mínimo en el departamento Soporte:**  */ 
SELECT MIN(SUELDO) AS MIN_SUELDO_DEPTO_SUPP
FROM EMPLEADOS, PUESTOS 
WHERE EMPLEADOS.PUESTO_ID = PUESTOS.ID 
AND PUESTOS.PUESTO = 'Soporte';


/* 11. **Suma de sueldos por puesto:**   */
SELECT PUESTOS.PUESTO, SUM(EMPLEADOS.SUELDO) AS SUM_SUELDOS
FROM EMPLEADOS, PUESTOS 
WHERE EMPLEADOS.PUESTO_ID = PUESTOS.ID 
GROUP BY PUESTOS.PUESTO;